server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: authentication
  datasource:
    username: root
    password: password
    url: jdbc:mysql://172.31.18.7:3306/users?useSSL=false&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  zipkin:
    base-url: http://172.31.28.239:9411
  rabbitmq: # address for rabbitmq
    addresses: 172.31.25.68:5672

security:
  jwt:
    token:
      secret-key: someSecretKey
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
eureka:
  client:
    service-url:
      defaultZone: http://172.31.25.68:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: 172.31.31.11

