server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: authentication
  datasource:
    username: root
    password: password
    url: jdbc:mysql://mysql:3306/fitnessbuddy?useSSL=false&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq: # address for rabbitmq
    addresses: rabbitmq:5672

security:
  jwt:
    token:
      secret-key: someSecretKey
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

