server:
  port: 8084
  error:
    include-stacktrace: never
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

